cd /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_23/perturbation/SymmetryFactor 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_23 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_23/perturbation/Energy 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_23 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_23/perturbation/FractionOne 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_23 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_23/perturbation/Frequencies 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_23 
