python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.1\ atm W1 R /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.3\ atm W1 R /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.5\ atm W1 R /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.7\ atm W1 R /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.9\ atm W1 R /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1\ atm W1 R /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1.5\ atm W1 R /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2\ atm W1 R /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2.5\ atm W1 R /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3\ atm W1 R /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3.5\ atm W1 R /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 4\ atm W1 R /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.1\ atm W1 P1 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.3\ atm W1 P1 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.5\ atm W1 P1 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.7\ atm W1 P1 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.9\ atm W1 P1 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1\ atm W1 P1 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1.5\ atm W1 P1 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2\ atm W1 P1 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2.5\ atm W1 P1 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3\ atm W1 P1 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3.5\ atm W1 P1 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 4\ atm W1 P1 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.1\ atm W1 P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.3\ atm W1 P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.5\ atm W1 P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.7\ atm W1 P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.9\ atm W1 P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1\ atm W1 P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1.5\ atm W1 P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2\ atm W1 P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2.5\ atm W1 P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3\ atm W1 P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3.5\ atm W1 P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 4\ atm W1 P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.1\ atm W1 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.3\ atm W1 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.5\ atm W1 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.7\ atm W1 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.9\ atm W1 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1\ atm W1 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1.5\ atm W1 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2\ atm W1 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2.5\ atm W1 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3\ atm W1 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3.5\ atm W1 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 4\ atm W1 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.1\ atm W1 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.3\ atm W1 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.5\ atm W1 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.7\ atm W1 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.9\ atm W1 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1\ atm W1 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1.5\ atm W1 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2\ atm W1 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2.5\ atm W1 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3\ atm W1 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3.5\ atm W1 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 4\ atm W1 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.1\ atm W1 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.3\ atm W1 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.5\ atm W1 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.7\ atm W1 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.9\ atm W1 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1\ atm W1 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1.5\ atm W1 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2\ atm W1 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2.5\ atm W1 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3\ atm W1 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3.5\ atm W1 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 4\ atm W1 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.1\ atm W1 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.3\ atm W1 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.5\ atm W1 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.7\ atm W1 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.9\ atm W1 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1\ atm W1 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1.5\ atm W1 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2\ atm W1 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2.5\ atm W1 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3\ atm W1 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3.5\ atm W1 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 4\ atm W1 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.1\ atm R P1 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.3\ atm R P1 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.5\ atm R P1 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.7\ atm R P1 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.9\ atm R P1 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1\ atm R P1 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1.5\ atm R P1 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2\ atm R P1 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2.5\ atm R P1 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3\ atm R P1 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3.5\ atm R P1 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 4\ atm R P1 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.1\ atm R P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.3\ atm R P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.5\ atm R P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.7\ atm R P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.9\ atm R P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1\ atm R P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1.5\ atm R P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2\ atm R P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2.5\ atm R P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3\ atm R P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3.5\ atm R P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 4\ atm R P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.1\ atm R P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.3\ atm R P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.5\ atm R P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.7\ atm R P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.9\ atm R P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1\ atm R P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1.5\ atm R P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2\ atm R P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2.5\ atm R P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3\ atm R P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3.5\ atm R P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 4\ atm R P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.1\ atm R P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.3\ atm R P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.5\ atm R P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.7\ atm R P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.9\ atm R P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1\ atm R P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1.5\ atm R P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2\ atm R P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2.5\ atm R P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3\ atm R P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3.5\ atm R P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 4\ atm R P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.1\ atm R P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.3\ atm R P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.5\ atm R P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.7\ atm R P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.9\ atm R P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1\ atm R P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1.5\ atm R P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2\ atm R P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2.5\ atm R P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3\ atm R P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3.5\ atm R P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 4\ atm R P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.1\ atm R P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.3\ atm R P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.5\ atm R P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.7\ atm R P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.9\ atm R P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1\ atm R P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1.5\ atm R P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2\ atm R P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2.5\ atm R P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3\ atm R P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3.5\ atm R P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 4\ atm R P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.1\ atm P1 P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.3\ atm P1 P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.5\ atm P1 P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.7\ atm P1 P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.9\ atm P1 P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1\ atm P1 P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1.5\ atm P1 P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2\ atm P1 P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2.5\ atm P1 P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3\ atm P1 P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3.5\ atm P1 P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 4\ atm P1 P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.1\ atm P1 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.3\ atm P1 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.5\ atm P1 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.7\ atm P1 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.9\ atm P1 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1\ atm P1 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1.5\ atm P1 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2\ atm P1 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2.5\ atm P1 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3\ atm P1 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3.5\ atm P1 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 4\ atm P1 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.1\ atm P1 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.3\ atm P1 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.5\ atm P1 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.7\ atm P1 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.9\ atm P1 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1\ atm P1 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1.5\ atm P1 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2\ atm P1 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2.5\ atm P1 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3\ atm P1 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3.5\ atm P1 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 4\ atm P1 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.1\ atm P1 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.3\ atm P1 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.5\ atm P1 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.7\ atm P1 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.9\ atm P1 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1\ atm P1 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1.5\ atm P1 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2\ atm P1 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2.5\ atm P1 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3\ atm P1 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3.5\ atm P1 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 4\ atm P1 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.1\ atm P1 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.3\ atm P1 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.5\ atm P1 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.7\ atm P1 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.9\ atm P1 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1\ atm P1 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1.5\ atm P1 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2\ atm P1 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2.5\ atm P1 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3\ atm P1 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3.5\ atm P1 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 4\ atm P1 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.1\ atm P2 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.3\ atm P2 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.5\ atm P2 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.7\ atm P2 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.9\ atm P2 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1\ atm P2 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1.5\ atm P2 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2\ atm P2 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2.5\ atm P2 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3\ atm P2 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3.5\ atm P2 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 4\ atm P2 P3 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.1\ atm P2 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.3\ atm P2 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.5\ atm P2 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.7\ atm P2 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.9\ atm P2 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1\ atm P2 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1.5\ atm P2 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2\ atm P2 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2.5\ atm P2 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3\ atm P2 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3.5\ atm P2 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 4\ atm P2 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.1\ atm P2 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.3\ atm P2 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.5\ atm P2 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.7\ atm P2 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.9\ atm P2 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1\ atm P2 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1.5\ atm P2 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2\ atm P2 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2.5\ atm P2 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3\ atm P2 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3.5\ atm P2 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 4\ atm P2 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.1\ atm P2 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.3\ atm P2 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.5\ atm P2 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.7\ atm P2 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.9\ atm P2 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1\ atm P2 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1.5\ atm P2 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2\ atm P2 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2.5\ atm P2 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3\ atm P2 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3.5\ atm P2 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 4\ atm P2 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.1\ atm P3 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.3\ atm P3 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.5\ atm P3 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.7\ atm P3 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.9\ atm P3 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1\ atm P3 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1.5\ atm P3 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2\ atm P3 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2.5\ atm P3 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3\ atm P3 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3.5\ atm P3 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 4\ atm P3 P4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.1\ atm P3 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.3\ atm P3 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.5\ atm P3 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.7\ atm P3 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.9\ atm P3 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1\ atm P3 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1.5\ atm P3 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2\ atm P3 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2.5\ atm P3 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3\ atm P3 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3.5\ atm P3 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 4\ atm P3 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.1\ atm P3 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.3\ atm P3 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.5\ atm P3 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.7\ atm P3 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.9\ atm P3 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1\ atm P3 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1.5\ atm P3 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2\ atm P3 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2.5\ atm P3 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3\ atm P3 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3.5\ atm P3 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 4\ atm P3 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.1\ atm P4 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.3\ atm P4 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.5\ atm P4 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.7\ atm P4 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.9\ atm P4 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1\ atm P4 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1.5\ atm P4 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2\ atm P4 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2.5\ atm P4 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3\ atm P4 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3.5\ atm P4 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 4\ atm P4 P5 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.1\ atm P4 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.3\ atm P4 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.5\ atm P4 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.7\ atm P4 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.9\ atm P4 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1\ atm P4 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1.5\ atm P4 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2\ atm P4 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2.5\ atm P4 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3\ atm P4 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3.5\ atm P4 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 4\ atm P4 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.1\ atm P5 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.3\ atm P5 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.5\ atm P5 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.7\ atm P5 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 0.9\ atm P5 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1\ atm P5 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 1.5\ atm P5 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2\ atm P5 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 2.5\ atm P5 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3\ atm P5 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 3.5\ atm P5 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
python MESS_rate_extractor.py ch3ar_W1_Energy_1_0.0.out 4\ atm P5 P6 /home/jmp/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_8/nominal False 
