cd /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_13/perturbation/Frequencies 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_13 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_13/perturbation/Energy 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_13 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_13/perturbation/SymmetryFactor 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_13 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_13/perturbation/ImaginaryFrequency 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_13 
