python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 0.1\ atm W1 R /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 0.3\ atm W1 R /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 0.5\ atm W1 R /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 0.7\ atm W1 R /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 0.9\ atm W1 R /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 1\ atm W1 R /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 1.5\ atm W1 R /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 2\ atm W1 R /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 2.5\ atm W1 R /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 3\ atm W1 R /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 3.5\ atm W1 R /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 4\ atm W1 R /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 0.1\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 0.3\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 0.5\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 0.7\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 0.9\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 1\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 1.5\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 2\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 2.5\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 3\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 3.5\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 4\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 0.1\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 0.3\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 0.5\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 0.7\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 0.9\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 1\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 1.5\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 2\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 2.5\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 3\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 3.5\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 4\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 0.1\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 0.3\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 0.5\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 0.7\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 0.9\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 1\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 1.5\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 2\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 2.5\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 3\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 3.5\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 4\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 0.1\ atm W1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 0.3\ atm W1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 0.5\ atm W1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 0.7\ atm W1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 0.9\ atm W1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 1\ atm W1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 1.5\ atm W1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 2\ atm W1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 2.5\ atm W1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 3\ atm W1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 3.5\ atm W1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 4\ atm W1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 0.1\ atm W1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 0.3\ atm W1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 0.5\ atm W1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 0.7\ atm W1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 0.9\ atm W1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 1\ atm W1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 1.5\ atm W1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 2\ atm W1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 2.5\ atm W1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 3\ atm W1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 3.5\ atm W1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 4\ atm W1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 0.1\ atm W1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 0.3\ atm W1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 0.5\ atm W1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 0.7\ atm W1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 0.9\ atm W1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 1\ atm W1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 1.5\ atm W1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 2\ atm W1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 2.5\ atm W1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 3\ atm W1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 3.5\ atm W1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
python MESS_rate_extractor.py ch4+o_W1_Energy_1_0.0.out 4\ atm W1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_2/nominal False 
