cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_1/perturbation/Energy 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_1 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_1/perturbation/Frequencies 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_1 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_1/perturbation/Sigmas 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_1 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_1/perturbation/SymmetryFactor 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_1 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_1/perturbation/Epsilons 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_1 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_1/perturbation/PowerOne 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_1 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_1/perturbation/FactorOne 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/ch4+o/calculation_1 
