cd /home/cel/MSI_Theory/PAPR-MESS_calculation/h+ho2=hooh/calculation_4/perturbation/Frequencies 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/h+ho2=hooh/calculation_4 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/h+ho2=hooh/calculation_4/perturbation/Energy 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/h+ho2=hooh/calculation_4 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/h+ho2=hooh/calculation_4/perturbation/NejScale 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/h+ho2=hooh/calculation_4 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/h+ho2=hooh/calculation_4/perturbation/SymmetryFactor 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/h+ho2=hooh/calculation_4 
