cd /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_28/perturbation/FactorOne 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_28 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_28/perturbation/FractionOne 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_28 
