python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.1\ atm W1 R /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.2\ atm W1 R /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.3\ atm W1 R /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.4\ atm W1 R /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.5\ atm W1 R /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.6\ atm W1 R /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.7\ atm W1 R /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.8\ atm W1 R /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.9\ atm W1 R /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1\ atm W1 R /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1.5\ atm W1 R /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2\ atm W1 R /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2.5\ atm W1 R /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3\ atm W1 R /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3.5\ atm W1 R /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 4\ atm W1 R /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.1\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.2\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.3\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.4\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.5\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.6\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.7\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.8\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.9\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1.5\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2.5\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3.5\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 4\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.1\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.2\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.3\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.4\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.5\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.6\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.7\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.8\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.9\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1.5\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2.5\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3.5\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 4\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.1\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.2\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.3\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.4\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.5\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.6\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.7\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.8\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.9\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1.5\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2.5\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3.5\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 4\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.1\ atm W1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.2\ atm W1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.3\ atm W1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.4\ atm W1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.5\ atm W1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.6\ atm W1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.7\ atm W1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.8\ atm W1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.9\ atm W1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1\ atm W1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1.5\ atm W1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2\ atm W1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2.5\ atm W1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3\ atm W1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3.5\ atm W1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 4\ atm W1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.1\ atm W1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.2\ atm W1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.3\ atm W1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.4\ atm W1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.5\ atm W1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.6\ atm W1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.7\ atm W1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.8\ atm W1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.9\ atm W1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1\ atm W1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1.5\ atm W1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2\ atm W1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2.5\ atm W1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3\ atm W1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3.5\ atm W1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 4\ atm W1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.1\ atm W1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.2\ atm W1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.3\ atm W1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.4\ atm W1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.5\ atm W1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.6\ atm W1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.7\ atm W1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.8\ atm W1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.9\ atm W1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1\ atm W1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1.5\ atm W1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2\ atm W1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2.5\ atm W1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3\ atm W1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3.5\ atm W1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 4\ atm W1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.1\ atm R P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.2\ atm R P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.3\ atm R P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.4\ atm R P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.5\ atm R P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.6\ atm R P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.7\ atm R P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.8\ atm R P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.9\ atm R P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1\ atm R P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1.5\ atm R P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2\ atm R P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2.5\ atm R P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3\ atm R P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3.5\ atm R P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 4\ atm R P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.1\ atm R P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.2\ atm R P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.3\ atm R P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.4\ atm R P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.5\ atm R P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.6\ atm R P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.7\ atm R P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.8\ atm R P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.9\ atm R P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1\ atm R P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1.5\ atm R P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2\ atm R P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2.5\ atm R P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3\ atm R P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3.5\ atm R P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 4\ atm R P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.1\ atm R P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.2\ atm R P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.3\ atm R P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.4\ atm R P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.5\ atm R P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.6\ atm R P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.7\ atm R P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.8\ atm R P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.9\ atm R P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1\ atm R P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1.5\ atm R P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2\ atm R P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2.5\ atm R P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3\ atm R P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3.5\ atm R P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 4\ atm R P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.1\ atm R P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.2\ atm R P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.3\ atm R P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.4\ atm R P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.5\ atm R P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.6\ atm R P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.7\ atm R P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.8\ atm R P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.9\ atm R P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1\ atm R P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1.5\ atm R P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2\ atm R P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2.5\ atm R P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3\ atm R P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3.5\ atm R P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 4\ atm R P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.1\ atm R P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.2\ atm R P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.3\ atm R P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.4\ atm R P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.5\ atm R P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.6\ atm R P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.7\ atm R P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.8\ atm R P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.9\ atm R P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1\ atm R P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1.5\ atm R P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2\ atm R P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2.5\ atm R P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3\ atm R P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3.5\ atm R P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 4\ atm R P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.1\ atm R P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.2\ atm R P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.3\ atm R P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.4\ atm R P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.5\ atm R P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.6\ atm R P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.7\ atm R P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.8\ atm R P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.9\ atm R P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1\ atm R P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1.5\ atm R P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2\ atm R P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2.5\ atm R P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3\ atm R P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3.5\ atm R P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 4\ atm R P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.1\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.2\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.3\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.4\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.5\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.6\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.7\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.8\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.9\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1.5\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2.5\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3.5\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 4\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.1\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.2\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.3\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.4\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.5\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.6\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.7\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.8\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.9\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1.5\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2.5\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3.5\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 4\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.1\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.2\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.3\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.4\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.5\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.6\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.7\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.8\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.9\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1.5\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2.5\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3.5\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 4\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.1\ atm P1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.2\ atm P1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.3\ atm P1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.4\ atm P1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.5\ atm P1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.6\ atm P1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.7\ atm P1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.8\ atm P1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.9\ atm P1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1\ atm P1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1.5\ atm P1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2\ atm P1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2.5\ atm P1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3\ atm P1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3.5\ atm P1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 4\ atm P1 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.1\ atm P1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.2\ atm P1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.3\ atm P1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.4\ atm P1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.5\ atm P1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.6\ atm P1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.7\ atm P1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.8\ atm P1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.9\ atm P1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1\ atm P1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1.5\ atm P1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2\ atm P1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2.5\ atm P1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3\ atm P1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3.5\ atm P1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 4\ atm P1 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.1\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.2\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.3\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.4\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.5\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.6\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.7\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.8\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.9\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1.5\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2.5\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3.5\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 4\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.1\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.2\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.3\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.4\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.5\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.6\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.7\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.8\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.9\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1.5\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2.5\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3.5\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 4\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.1\ atm P2 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.2\ atm P2 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.3\ atm P2 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.4\ atm P2 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.5\ atm P2 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.6\ atm P2 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.7\ atm P2 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.8\ atm P2 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.9\ atm P2 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1\ atm P2 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1.5\ atm P2 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2\ atm P2 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2.5\ atm P2 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3\ atm P2 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3.5\ atm P2 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 4\ atm P2 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.1\ atm P2 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.2\ atm P2 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.3\ atm P2 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.4\ atm P2 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.5\ atm P2 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.6\ atm P2 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.7\ atm P2 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.8\ atm P2 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.9\ atm P2 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1\ atm P2 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1.5\ atm P2 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2\ atm P2 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2.5\ atm P2 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3\ atm P2 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3.5\ atm P2 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 4\ atm P2 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.1\ atm P3 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.2\ atm P3 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.3\ atm P3 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.4\ atm P3 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.5\ atm P3 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.6\ atm P3 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.7\ atm P3 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.8\ atm P3 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.9\ atm P3 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1\ atm P3 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1.5\ atm P3 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2\ atm P3 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2.5\ atm P3 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3\ atm P3 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3.5\ atm P3 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 4\ atm P3 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.1\ atm P3 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.2\ atm P3 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.3\ atm P3 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.4\ atm P3 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.5\ atm P3 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.6\ atm P3 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.7\ atm P3 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.8\ atm P3 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.9\ atm P3 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1\ atm P3 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1.5\ atm P3 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2\ atm P3 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2.5\ atm P3 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3\ atm P3 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3.5\ atm P3 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 4\ atm P3 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.1\ atm P3 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.2\ atm P3 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.3\ atm P3 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.4\ atm P3 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.5\ atm P3 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.6\ atm P3 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.7\ atm P3 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.8\ atm P3 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.9\ atm P3 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1\ atm P3 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1.5\ atm P3 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2\ atm P3 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2.5\ atm P3 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3\ atm P3 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3.5\ atm P3 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 4\ atm P3 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.1\ atm P4 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.2\ atm P4 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.3\ atm P4 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.4\ atm P4 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.5\ atm P4 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.6\ atm P4 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.7\ atm P4 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.8\ atm P4 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.9\ atm P4 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1\ atm P4 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1.5\ atm P4 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2\ atm P4 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2.5\ atm P4 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3\ atm P4 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3.5\ atm P4 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 4\ atm P4 P5 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.1\ atm P4 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.2\ atm P4 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.3\ atm P4 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.4\ atm P4 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.5\ atm P4 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.6\ atm P4 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.7\ atm P4 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.8\ atm P4 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.9\ atm P4 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1\ atm P4 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1.5\ atm P4 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2\ atm P4 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2.5\ atm P4 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3\ atm P4 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3.5\ atm P4 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 4\ atm P4 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.1\ atm P5 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.2\ atm P5 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.3\ atm P5 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.4\ atm P5 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.5\ atm P5 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.6\ atm P5 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.7\ atm P5 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.8\ atm P5 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 0.9\ atm P5 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1\ atm P5 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 1.5\ atm P5 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2\ atm P5 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 2.5\ atm P5 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3\ atm P5 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 3.5\ atm P5 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
python MESS_rate_extractor.py ch3ar_colrel_Epsilons_0.1.out 4\ atm P5 P6 /home/cel/MSI_Theory/PAPR-MESS_calculation/ch3ar/calculation_3/perturbation False 
