cd /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_4/perturbation/Frequencies 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_4 
cd /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_4/perturbation/Energy 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_4 
cd /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_4/perturbation/2143 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
