python MESS_rate_extractor.py c2h6rad_W1_Energy_1_0.0.out 0.1\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_23/nominal False 
python MESS_rate_extractor.py c2h6rad_W1_Energy_1_0.0.out 0.5\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_23/nominal False 
python MESS_rate_extractor.py c2h6rad_W1_Energy_1_0.0.out 1\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_23/nominal False 
python MESS_rate_extractor.py c2h6rad_W1_Energy_1_0.0.out 3\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_23/nominal False 
python MESS_rate_extractor.py c2h6rad_W1_Energy_1_0.0.out 4\ atm W1 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_23/nominal False 
python MESS_rate_extractor.py c2h6rad_W1_Energy_1_0.0.out 0.1\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_23/nominal False 
python MESS_rate_extractor.py c2h6rad_W1_Energy_1_0.0.out 0.5\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_23/nominal False 
python MESS_rate_extractor.py c2h6rad_W1_Energy_1_0.0.out 1\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_23/nominal False 
python MESS_rate_extractor.py c2h6rad_W1_Energy_1_0.0.out 3\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_23/nominal False 
python MESS_rate_extractor.py c2h6rad_W1_Energy_1_0.0.out 4\ atm W1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_23/nominal False 
python MESS_rate_extractor.py c2h6rad_W1_Energy_1_0.0.out 0.1\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_23/nominal False 
python MESS_rate_extractor.py c2h6rad_W1_Energy_1_0.0.out 0.5\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_23/nominal False 
python MESS_rate_extractor.py c2h6rad_W1_Energy_1_0.0.out 1\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_23/nominal False 
python MESS_rate_extractor.py c2h6rad_W1_Energy_1_0.0.out 3\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_23/nominal False 
python MESS_rate_extractor.py c2h6rad_W1_Energy_1_0.0.out 4\ atm W1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_23/nominal False 
python MESS_rate_extractor.py c2h6rad_W1_Energy_1_0.0.out 0.1\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_23/nominal False 
python MESS_rate_extractor.py c2h6rad_W1_Energy_1_0.0.out 0.5\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_23/nominal False 
python MESS_rate_extractor.py c2h6rad_W1_Energy_1_0.0.out 1\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_23/nominal False 
python MESS_rate_extractor.py c2h6rad_W1_Energy_1_0.0.out 3\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_23/nominal False 
python MESS_rate_extractor.py c2h6rad_W1_Energy_1_0.0.out 4\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_23/nominal False 
python MESS_rate_extractor.py c2h6rad_W1_Energy_1_0.0.out 0.1\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_23/nominal False 
python MESS_rate_extractor.py c2h6rad_W1_Energy_1_0.0.out 0.5\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_23/nominal False 
python MESS_rate_extractor.py c2h6rad_W1_Energy_1_0.0.out 1\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_23/nominal False 
python MESS_rate_extractor.py c2h6rad_W1_Energy_1_0.0.out 3\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_23/nominal False 
python MESS_rate_extractor.py c2h6rad_W1_Energy_1_0.0.out 4\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_23/nominal False 
python MESS_rate_extractor.py c2h6rad_W1_Energy_1_0.0.out 0.1\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_23/nominal False 
python MESS_rate_extractor.py c2h6rad_W1_Energy_1_0.0.out 0.5\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_23/nominal False 
python MESS_rate_extractor.py c2h6rad_W1_Energy_1_0.0.out 1\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_23/nominal False 
python MESS_rate_extractor.py c2h6rad_W1_Energy_1_0.0.out 3\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_23/nominal False 
python MESS_rate_extractor.py c2h6rad_W1_Energy_1_0.0.out 4\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_23/nominal False 
