python MESS_rate_extractor.py CH2O_Hot_All_W0_Energy_1_0.0.out 1.0\ atm W4 W5c /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_26/nominal False 
python MESS_rate_extractor.py CH2O_Hot_All_W0_Energy_1_0.0.out 1.0\ atm W5c W4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_26/nominal False 
python MESS_rate_extractor.py CH2O_Hot_All_W0_Energy_1_0.0.out 1.0\ atm W4 W5t /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_26/nominal False 
python MESS_rate_extractor.py CH2O_Hot_All_W0_Energy_1_0.0.out 1.0\ atm W5t W4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_26/nominal False 
python MESS_rate_extractor.py CH2O_Hot_All_W0_Energy_1_0.0.out 1.0\ atm W4 S1 /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_26/nominal False 
python MESS_rate_extractor.py CH2O_Hot_All_W0_Energy_1_0.0.out 1.0\ atm S1 W4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_26/nominal False 
python MESS_rate_extractor.py CH2O_Hot_All_W0_Energy_1_0.0.out 1.0\ atm W4 P1 /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_26/nominal False 
python MESS_rate_extractor.py CH2O_Hot_All_W0_Energy_1_0.0.out 1.0\ atm P1 W4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_26/nominal False 
python MESS_rate_extractor.py CH2O_Hot_All_W0_Energy_1_0.0.out 1.0\ atm W4 P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_26/nominal False 
python MESS_rate_extractor.py CH2O_Hot_All_W0_Energy_1_0.0.out 1.0\ atm P2 W4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_26/nominal False 
python MESS_rate_extractor.py CH2O_Hot_All_W0_Energy_1_0.0.out 1.0\ atm W4 Pescape /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_26/nominal False 
python MESS_rate_extractor.py CH2O_Hot_All_W0_Energy_1_0.0.out 1.0\ atm Pescape W4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_26/nominal False 
python MESS_rate_extractor.py CH2O_Hot_All_W0_Energy_1_0.0.out 1.0\ atm W4 P2143 /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_26/nominal False 
python MESS_rate_extractor.py CH2O_Hot_All_W0_Energy_1_0.0.out 1.0\ atm P2143 W4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_26/nominal False 
python MESS_rate_extractor.py CH2O_Hot_All_W0_Energy_1_0.0.out 1.0\ atm W4 P2141 /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_26/nominal False 
python MESS_rate_extractor.py CH2O_Hot_All_W0_Energy_1_0.0.out 1.0\ atm P2141 W4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_26/nominal False 
python MESS_rate_extractor.py CH2O_Hot_All_W0_Energy_1_0.0.out 1.0\ atm W4 P41 /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_26/nominal False 
python MESS_rate_extractor.py CH2O_Hot_All_W0_Energy_1_0.0.out 1.0\ atm P41 W4 /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_26/nominal False 
python MESS_rate_extractor.py CH2O_Hot_All_W0_Energy_1_0.0.out 1.0\ atm W5c W5t /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_26/nominal False 
python MESS_rate_extractor.py CH2O_Hot_All_W0_Energy_1_0.0.out 1.0\ atm W5t W5c /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_26/nominal False 
python MESS_rate_extractor.py CH2O_Hot_All_W0_Energy_1_0.0.out 1.0\ atm W5c P1 /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_26/nominal False 
python MESS_rate_extractor.py CH2O_Hot_All_W0_Energy_1_0.0.out 1.0\ atm P1 W5c /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_26/nominal False 
python MESS_rate_extractor.py CH2O_Hot_All_W0_Energy_1_0.0.out 1.0\ atm W5c P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_26/nominal False 
python MESS_rate_extractor.py CH2O_Hot_All_W0_Energy_1_0.0.out 1.0\ atm P2 W5c /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_26/nominal False 
python MESS_rate_extractor.py CH2O_Hot_All_W0_Energy_1_0.0.out 1.0\ atm W5c Pescape /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_26/nominal False 
python MESS_rate_extractor.py CH2O_Hot_All_W0_Energy_1_0.0.out 1.0\ atm Pescape W5c /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_26/nominal False 
python MESS_rate_extractor.py CH2O_Hot_All_W0_Energy_1_0.0.out 1.0\ atm W5t P1 /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_26/nominal False 
python MESS_rate_extractor.py CH2O_Hot_All_W0_Energy_1_0.0.out 1.0\ atm P1 W5t /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_26/nominal False 
python MESS_rate_extractor.py CH2O_Hot_All_W0_Energy_1_0.0.out 1.0\ atm W5t P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_26/nominal False 
python MESS_rate_extractor.py CH2O_Hot_All_W0_Energy_1_0.0.out 1.0\ atm P2 W5t /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_26/nominal False 
python MESS_rate_extractor.py CH2O_Hot_All_W0_Energy_1_0.0.out 1.0\ atm P1 P2 /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_26/nominal False 
