python MESS_rate_extractor.py nh2no_B12_NejScale_1_0.1.out 1.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B13_NejScale_1_0.1.out 1.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B7_NejScale_1_0.1.out 1.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B12_NejScale_1_0.1.out 1.0\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B13_NejScale_1_0.1.out 1.0\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B7_NejScale_1_0.1.out 1.0\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B12_NejScale_1_0.1.out 1.0\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B13_NejScale_1_0.1.out 1.0\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B7_NejScale_1_0.1.out 1.0\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B12_NejScale_1_0.1.out 1.0\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B13_NejScale_1_0.1.out 1.0\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B7_NejScale_1_0.1.out 1.0\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B12_NejScale_1_0.1.out 1.0\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B13_NejScale_1_0.1.out 1.0\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B7_NejScale_1_0.1.out 1.0\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B12_NejScale_1_0.1.out 1.0\ atm P4 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B13_NejScale_1_0.1.out 1.0\ atm P4 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B7_NejScale_1_0.1.out 1.0\ atm P4 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
