cd /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_44/perturbation/Frequencies 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_44 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_44/perturbation/Energy 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_44 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_44/perturbation/SymmetryFactor 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_44 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_44/perturbation/ImaginaryFrequency 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_44 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_44/perturbation/HinderRotor 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/c2h6rad/calculation_44 
