cd /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH3+OHtripletabs/calculation_18/perturbation/Energy 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH3+OHtripletabs/calculation_18 
cd /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH3+OHtripletabs/calculation_18/perturbation/Frequencies 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH3+OHtripletabs/calculation_18 
cd /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH3+OHtripletabs/calculation_18/perturbation/VariationalHinderRotor 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
