cd /home/cel/MSI_Theory/PAPR-MESS_calculation/absc2h5+h/calculation_15/perturbation/Energy 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/absc2h5+h/calculation_15 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/absc2h5+h/calculation_15/perturbation/Frequencies 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/absc2h5+h/calculation_15 
cd /home/cel/MSI_Theory/PAPR-MESS_calculation/absc2h5+h/calculation_15/perturbation/ImaginaryFrequency 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
