python MESS_rate_extractor.py methink_colrel_FactorTwo_0.1.out 0.1\ atm W4 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_24/perturbation False 
python MESS_rate_extractor.py methink_colrel_FactorTwo_0.1.out 0.5\ atm W4 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_24/perturbation False 
python MESS_rate_extractor.py methink_colrel_FactorTwo_0.1.out 1.0\ atm W4 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_24/perturbation False 
python MESS_rate_extractor.py methink_colrel_FactorTwo_0.1.out 2.0\ atm W4 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_24/perturbation False 
python MESS_rate_extractor.py methink_colrel_FactorTwo_0.1.out 4.0\ atm W4 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_24/perturbation False 
python MESS_rate_extractor.py methink_colrel_FactorTwo_0.1.out 0.1\ atm W4 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_24/perturbation False 
python MESS_rate_extractor.py methink_colrel_FactorTwo_0.1.out 0.5\ atm W4 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_24/perturbation False 
python MESS_rate_extractor.py methink_colrel_FactorTwo_0.1.out 1.0\ atm W4 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_24/perturbation False 
python MESS_rate_extractor.py methink_colrel_FactorTwo_0.1.out 2.0\ atm W4 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_24/perturbation False 
python MESS_rate_extractor.py methink_colrel_FactorTwo_0.1.out 4.0\ atm W4 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_24/perturbation False 
python MESS_rate_extractor.py methink_colrel_FactorTwo_0.1.out 0.1\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_24/perturbation False 
python MESS_rate_extractor.py methink_colrel_FactorTwo_0.1.out 0.5\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_24/perturbation False 
python MESS_rate_extractor.py methink_colrel_FactorTwo_0.1.out 1.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_24/perturbation False 
python MESS_rate_extractor.py methink_colrel_FactorTwo_0.1.out 2.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_24/perturbation False 
python MESS_rate_extractor.py methink_colrel_FactorTwo_0.1.out 4.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_24/perturbation False 
