python MESS_rate_extractor.py hco_B1_Frequencies_1_34.9759.out 0.1\ atm W1 P0 /home/cel/MSI_Theory/PAPR-MESS_calculation/hco/calculation_3/perturbation False 
python MESS_rate_extractor.py hco_B1_Frequencies_1_34.9759.out 0.5\ atm W1 P0 /home/cel/MSI_Theory/PAPR-MESS_calculation/hco/calculation_3/perturbation False 
python MESS_rate_extractor.py hco_B1_Frequencies_1_34.9759.out 1.0\ atm W1 P0 /home/cel/MSI_Theory/PAPR-MESS_calculation/hco/calculation_3/perturbation False 
python MESS_rate_extractor.py hco_B1_Frequencies_1_34.9759.out 2.0\ atm W1 P0 /home/cel/MSI_Theory/PAPR-MESS_calculation/hco/calculation_3/perturbation False 
python MESS_rate_extractor.py hco_B1_Frequencies_1_34.9759.out 4.0\ atm W1 P0 /home/cel/MSI_Theory/PAPR-MESS_calculation/hco/calculation_3/perturbation False 
python MESS_rate_extractor.py hco_W1_Frequencies_1_0.1.out 0.1\ atm W1 P0 /home/cel/MSI_Theory/PAPR-MESS_calculation/hco/calculation_3/perturbation False 
python MESS_rate_extractor.py hco_W1_Frequencies_1_0.1.out 0.5\ atm W1 P0 /home/cel/MSI_Theory/PAPR-MESS_calculation/hco/calculation_3/perturbation False 
python MESS_rate_extractor.py hco_W1_Frequencies_1_0.1.out 1.0\ atm W1 P0 /home/cel/MSI_Theory/PAPR-MESS_calculation/hco/calculation_3/perturbation False 
python MESS_rate_extractor.py hco_W1_Frequencies_1_0.1.out 2.0\ atm W1 P0 /home/cel/MSI_Theory/PAPR-MESS_calculation/hco/calculation_3/perturbation False 
python MESS_rate_extractor.py hco_W1_Frequencies_1_0.1.out 4.0\ atm W1 P0 /home/cel/MSI_Theory/PAPR-MESS_calculation/hco/calculation_3/perturbation False 
python MESS_rate_extractor.py hco_P0_Frequencies_1_34.9759.out 0.1\ atm W1 P0 /home/cel/MSI_Theory/PAPR-MESS_calculation/hco/calculation_3/perturbation False 
python MESS_rate_extractor.py hco_P0_Frequencies_1_34.9759.out 0.5\ atm W1 P0 /home/cel/MSI_Theory/PAPR-MESS_calculation/hco/calculation_3/perturbation False 
python MESS_rate_extractor.py hco_P0_Frequencies_1_34.9759.out 1.0\ atm W1 P0 /home/cel/MSI_Theory/PAPR-MESS_calculation/hco/calculation_3/perturbation False 
python MESS_rate_extractor.py hco_P0_Frequencies_1_34.9759.out 2.0\ atm W1 P0 /home/cel/MSI_Theory/PAPR-MESS_calculation/hco/calculation_3/perturbation False 
python MESS_rate_extractor.py hco_P0_Frequencies_1_34.9759.out 4.0\ atm W1 P0 /home/cel/MSI_Theory/PAPR-MESS_calculation/hco/calculation_3/perturbation False 
