python MESS_rate_extractor.py methink_W0_Energy_1_0.0.out 0.1\ atm W4 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_25/nominal False 
python MESS_rate_extractor.py methink_W0_Energy_1_0.0.out 0.5\ atm W4 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_25/nominal False 
python MESS_rate_extractor.py methink_W0_Energy_1_0.0.out 1.0\ atm W4 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_25/nominal False 
python MESS_rate_extractor.py methink_W0_Energy_1_0.0.out 2.0\ atm W4 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_25/nominal False 
python MESS_rate_extractor.py methink_W0_Energy_1_0.0.out 4.0\ atm W4 P1 /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_25/nominal False 
python MESS_rate_extractor.py methink_W0_Energy_1_0.0.out 0.1\ atm W4 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_25/nominal False 
python MESS_rate_extractor.py methink_W0_Energy_1_0.0.out 0.5\ atm W4 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_25/nominal False 
python MESS_rate_extractor.py methink_W0_Energy_1_0.0.out 1.0\ atm W4 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_25/nominal False 
python MESS_rate_extractor.py methink_W0_Energy_1_0.0.out 2.0\ atm W4 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_25/nominal False 
python MESS_rate_extractor.py methink_W0_Energy_1_0.0.out 4.0\ atm W4 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_25/nominal False 
python MESS_rate_extractor.py methink_W0_Energy_1_0.0.out 0.1\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_25/nominal False 
python MESS_rate_extractor.py methink_W0_Energy_1_0.0.out 0.5\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_25/nominal False 
python MESS_rate_extractor.py methink_W0_Energy_1_0.0.out 1.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_25/nominal False 
python MESS_rate_extractor.py methink_W0_Energy_1_0.0.out 2.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_25/nominal False 
python MESS_rate_extractor.py methink_W0_Energy_1_0.0.out 4.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/methink/calculation_25/nominal False 
