cd /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_13/perturbation/Frequencies 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_13 
cd /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_13/perturbation/Energy 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_13 
cd /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_13/perturbation/ImaginaryFrequency 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_13 
cd /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_13/perturbation/SymmetryFactor 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_13 
cd /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_13/perturbation/FractionOne 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_13 
cd /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_13/perturbation/PowerOne 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_13 
cd /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_13/perturbation/FactorOne 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_13 
cd /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_13/perturbation/Sigmas 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_13 
cd /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_13/perturbation/Epsilons 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_13 
cd /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_13/perturbation/FactorTwo 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_13 
cd /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_13/perturbation/PowerTwo 
sh perturb_bash.sh 
rm perturb_bash.sh 
sh rate_bash.sh 
rm MESS_rate_extractor.py 
rm rate_bash.sh 
cd /home/jmp/MSI_Theory/PAPR-MESS_calculation/CH2O_Hot_All/calculation_13 
