python MESS_rate_extractor.py nh2no_W1_Frequencies_1_0.1.out 1.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_W2b_Frequencies_1_0.1.out 1.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_W3b_Frequencies_1_0.1.out 1.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B8_Frequencies_1_0.1.out 1.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B9_Frequencies_1_0.1.out 1.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_W2a_Frequencies_1_0.1.out 1.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B11_Frequencies_1_0.1.out 1.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B16_Frequencies_1_0.1.out 1.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_W3a_Frequencies_1_0.1.out 1.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B10_Frequencies_1_0.1.out 1.0\ atm P1 P2 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_W1_Frequencies_1_0.1.out 1.0\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_W2b_Frequencies_1_0.1.out 1.0\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_W3b_Frequencies_1_0.1.out 1.0\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B8_Frequencies_1_0.1.out 1.0\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B9_Frequencies_1_0.1.out 1.0\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_W2a_Frequencies_1_0.1.out 1.0\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B11_Frequencies_1_0.1.out 1.0\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B16_Frequencies_1_0.1.out 1.0\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_W3a_Frequencies_1_0.1.out 1.0\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B10_Frequencies_1_0.1.out 1.0\ atm P1 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_W1_Frequencies_1_0.1.out 1.0\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_W2b_Frequencies_1_0.1.out 1.0\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_W3b_Frequencies_1_0.1.out 1.0\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B8_Frequencies_1_0.1.out 1.0\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B9_Frequencies_1_0.1.out 1.0\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_W2a_Frequencies_1_0.1.out 1.0\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B11_Frequencies_1_0.1.out 1.0\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B16_Frequencies_1_0.1.out 1.0\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_W3a_Frequencies_1_0.1.out 1.0\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B10_Frequencies_1_0.1.out 1.0\ atm P1 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_W1_Frequencies_1_0.1.out 1.0\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_W2b_Frequencies_1_0.1.out 1.0\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_W3b_Frequencies_1_0.1.out 1.0\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B8_Frequencies_1_0.1.out 1.0\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B9_Frequencies_1_0.1.out 1.0\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_W2a_Frequencies_1_0.1.out 1.0\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B11_Frequencies_1_0.1.out 1.0\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B16_Frequencies_1_0.1.out 1.0\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_W3a_Frequencies_1_0.1.out 1.0\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B10_Frequencies_1_0.1.out 1.0\ atm P2 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_W1_Frequencies_1_0.1.out 1.0\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_W2b_Frequencies_1_0.1.out 1.0\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_W3b_Frequencies_1_0.1.out 1.0\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B8_Frequencies_1_0.1.out 1.0\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B9_Frequencies_1_0.1.out 1.0\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_W2a_Frequencies_1_0.1.out 1.0\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B11_Frequencies_1_0.1.out 1.0\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B16_Frequencies_1_0.1.out 1.0\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_W3a_Frequencies_1_0.1.out 1.0\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B10_Frequencies_1_0.1.out 1.0\ atm P2 P4 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_W1_Frequencies_1_0.1.out 1.0\ atm P4 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_W2b_Frequencies_1_0.1.out 1.0\ atm P4 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_W3b_Frequencies_1_0.1.out 1.0\ atm P4 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B8_Frequencies_1_0.1.out 1.0\ atm P4 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B9_Frequencies_1_0.1.out 1.0\ atm P4 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_W2a_Frequencies_1_0.1.out 1.0\ atm P4 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B11_Frequencies_1_0.1.out 1.0\ atm P4 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B16_Frequencies_1_0.1.out 1.0\ atm P4 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_W3a_Frequencies_1_0.1.out 1.0\ atm P4 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
python MESS_rate_extractor.py nh2no_B10_Frequencies_1_0.1.out 1.0\ atm P4 P3 /home/cel/MSI_Theory/PAPR-MESS_calculation/nh2no/calculation_2/perturbation False 
